### ISSUE TITLE
App Crashes While Running On Android API 23

### ISSUE THREAD

**Issue by ankit1057** [sazid/Browse#7]
09-10 16:04:48.175 18897-18979/com.mohammedsazid.android.browse E/cr_VariationsUtils: Failed reading seed file "/data/user/0/com.mohammedsazid.android.browse/app_webview/variations_seed_new": /data/user/0/com.mohammedsazid.android.browse/app_webview/variations_seed_new: open failed: ENOENT (No such file or directory)
09-10 16:04:48.638 18897-19025/com.mohammedsazid.android.browse E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
09-10 16:04:57.918 18897-18897/com.mohammedsazid.android.browse E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.mohammedsazid.android.browse, PID: 18897
                                                                                  java.lang.IllegalArgumentException: Expected receiver of type com.mohammedsazid.android.browse.MainActivity, but got android.support.v7.widget.TintContextWrapper
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at android.view.View$DeclaredOnClickListener.onClick(View.java:4463)
                                                                                      at android.view.View.performClick(View.java:5214)
                                                                                      at android.view.View$PerformClick.run(View.java:21173)
                                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sazid** [comment]
Thanks @ankit1057 for the report :)
Can you please tell me, how it happened? And if you manage to fix it yourself, feel free to open a pull request :D

**Comment by ankit1057** [comment]
I just forked the code and cloned it and ran the app. The menu won't open.
When I click on the three dots, the app crashed.

**Comment by sazid** [comment]
@ankit1057 Can you try pulling in the latest code and run it? I've updated the libraries and gradle.

**Comment by sazid** [comment]
It's available to download from Playstore now: https://play.google.com/store/apps/details?id=com.mohammedsazid.android.browse

**Comment by sazid** [comment]
Closing for now, if you experience the same problem feel free to reopen the issue!

**Comment by ankit1057** [comment]
Thank you so much Sir, it worked. I gotta learn a lot from your project.
The implementation is super cool.

**Comment by sazid** [comment]
You're welcome!

**Comment by ankit1057** [comment]
Today I Ran The App Again and it crashed whereas the playstore version doesn't crash

**Comment by sazid** [comment]
Same error or a different error? I can't seem to reproduce it on my end.
